### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by achinverma** [breezedave/android-anpr#1]
hi
i have imported this in eclipse but when i run this demo i got below error
11-06 11:31:55.689: D/OpenCV/StaticHelper(19325): First attempt to load libs
11-06 11:31:55.689: D/OpenCV/StaticHelper(19325): Trying to init OpenCV libs
11-06 11:31:55.689: D/OpenCV/StaticHelper(19325): Trying to load library opencv_java
11-06 11:31:55.690: D/OpenCV/StaticHelper(19325): Cannot load library "opencv_java"
11-06 11:31:55.690: W/System.err(19325): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.DVLA.testapp.app-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libopencv_java.so"
11-06 11:31:55.691: W/System.err(19325):    at java.lang.Runtime.loadLibrary(Runtime.java:366)
11-06 11:31:55.691: W/System.err(19325):    at java.lang.System.loadLibrary(System.java:989)
11-06 11:31:55.691: W/System.err(19325):    at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:54)
11-06 11:31:55.692: W/System.err(19325):    at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:85)
11-06 11:31:55.692: W/System.err(19325):    at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:29)
11-06 11:31:55.692: W/System.err(19325):    at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:51)
11-06 11:31:55.692: W/System.err(19325):    at com.DVLA.testapp.app.MainActivity.onCreate(MainActivity.java:44)
11-06 11:31:55.692: W/System.err(19325):    at android.app.Activity.performCreate(Activity.java:5933)
11-06 11:31:55.692: W/System.err(19325):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
11-06 11:31:55.692: W/System.err(19325):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
11-06 11:31:55.692: W/System.err(19325):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
11-06 11:31:55.692: W/System.err(19325):    at android.app.ActivityThread.access$800(ActivityThread.java:144)
11-06 11:31:55.692: W/System.err(19325):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
11-06 11:31:55.692: W/System.err(19325):    at android.os.Handler.dispatchMessage(Handler.java:102)
11-06 11:31:55.692: W/System.err(19325):    at android.os.Looper.loop(Looper.java:135)
11-06 11:31:55.692: W/System.err(19325):    at android.app.ActivityThread.main(ActivityThread.java:5221)
11-06 11:31:55.692: W/System.err(19325):    at java.lang.reflect.Method.invoke(Native Method)
11-06 11:31:55.692: W/System.err(19325):    at java.lang.reflect.Method.invoke(Method.java:372)
11-06 11:31:55.692: W/System.err(19325):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
11-06 11:31:55.692: W/System.err(19325):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

![untitled](https://cloud.githubusercontent.com/assets/2811593/10990712/2c123928-847c-11e5-9806-53e77993d3df.png)

**Comment by breezedave** [comment]
Couple of questions:
- What versions of the Android SDK do you have installed?
- What device are you using for testing

**Comment by achinverma** [comment]
i am using 5.0.1 android sdk and
i have tested it on nexus 4(5.0) and on Moto g(5.1.1)
 please can you guide me why i am getting 
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.DVLA.testapp.app-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libopencv_java.so"
